
#baseURL = 'http://98.45.192.245:8123/html_guides/aureli_photography/'
baseURL = 'https://aureliphotography.github.io/portfolio/'

languageCode = 'en-us'
title = 'Aureli Photography'

theme = "gallery"
